### PR TITLE
Fixed CTD on macs at "Loading Graphics..."

### PR DESCRIPTION
**Pull request by neuralroberts**
4241;64;76;173;Northern Lakes3;x in definitions.csv was causing the crash. Recoloring these lakes in provinces.bmp resolved the crash.

### CODE REVIEW

**Comment by thecookiemaker** [comment]
I reviewed the changes. you have changed about 10 provinces. can you try changing each of these provinces one at a time to see if you can determine which of them is the culprit? 
provinces

**Comment by thecookiemaker** [comment]
additionally the provinces mentioned in 4241;64;76;173;Northern Lakes3;x are all up north on the opposite end of the map. Does changing definition.csv 4241 to an unused color resolve the issue without recoloring provinces.bmp?
provinces

**Comment by neuralroberts** [comment]
Looking at your first pictures, I must have mistakenly recolored all provinces within a threshold. I tried some more things:
1.  Recoloring only 4241 (Northern Lakes3) with the same color doesn't stop the crash.
2.  Changing 4241 to an unused color in definitions.csv and provinces.bmp doesn't stop the crash. 
3.  Removing 4241 from definitions.csv stops the crash, but the lakes are then named ANY_ALL in-game.
4.  Individually recoloring many (but not all) provinces to match 4241's color stops the crash, but these provinces are then called "Northern Lakes" in game. This worked for almost all of the water provinces I tried, and some of the land. Unfortunately didn't work with the other Northern Lakes provinces. 

I'm not sure what else to try. Any ideas?

**Comment by thecookiemaker** [comment]
does removing 4241 and coloring those lakes black work?

**Comment by thecookiemaker** [comment]
If it doesn't we can just remove 4241 and have the lakes named ANY_ALL until a better fix is found.

**Comment by neuralroberts** [comment]
Looks like coloring the lakes black and removing 4241 from definitions worked.

**Comment by thecookiemaker** [comment]
ok I will do that to the main one then. Thanks for testing that.

**Pull request closed without merging**
