### PR TITLE
Adjust Obispo and Santa Barbara with a little local flavor:

### PR DESCRIPTION
**Pull request by Idhrendur**
- Pismo moved to Obispo and renamed to Pismo Beach
- Solvang added to Santa Barbara as a replacement
- Hearst Castle is now the main holding in Obispo, as its an already-existing castle that shrugs off earthquakes and is famous
- Baywood renamed to Morro bay because that's the name known locally
- Several baronies that are the sites of California Missions are now temples
- The ruling dynasty of Obispo is now Madonna, because if they can convince everyone that a mountain is named after them, they're gonna be around for the long haul.

### CODE REVIEW

**Comment by vinnypossum** [comment]
I love your changes. Would you be interested in collaborating on a California Flavor submod?

**Comment by Idhrendur** [comment]
Sure, though I'm not sure how much help I'd be with the rest of the state. I only was able to do this from having grown up in SLO county and noticing things were off.

**Comment by SteelyGlint** [comment]
I appreciate the suggestion, but I'm not sure if removing existing holdings would break save games created before the change. Without knowing for sure that it won't, I'm not going to include changes that are mostly cosmetic.

**Comment by GSonderling** [comment]
AtE has changed a lot since this was posted and old saves don't work on new versions anyway. I would recommend using this.

**Pull request closed without merging**
