### PR TITLE
Fixing Investiture Fixes

### PR DESCRIPTION
**Pull request by Dryhad**
Ursuline theocracies are now enatic, gender law changes are slightly less hacky.
As a bonus, the First Order of Lady Liberty is also enatic as per lore. (Feel free to change the First Lady's name/traits/etc., I just needed to create a female character to start things off)

### CODE REVIEW

**Comment by SteelyGlint** [comment]
This is intended to work in conjunction with GSonderling's changes, correct? Have you confirmed that the changes have the desired behavior, by killing the appropriate characters with console commands?

**Comment by Dryhad** [comment]
Yes, this has been tested with the console on the current patch. Many patches ago, I also ran a proper game with similar changes with success (although this submission is built on the current state of the mod as I mentioned).
This submission incorporates GSonderling's changes to succession_laws.txt and all other additions to the mod at time of writing. I don't believe there is any conflict with GSonderling's pending pull requests but they were not specifically taken into account.

**Comment by VoltSpark** [comment]
This is cleaner than my fix, though if this is implemented, the event file I put my events in should probably be removed, rather than just removing its on_action references.

On the topic of investiture, is the absence of a crown_laws file deliberate? Without that file, High Church and Ursuline realms essentially permanently have Free Investiture. (Which may or may not be appropriate for High Church, though the Ursulines are essentially Catholics with female priests, so I would think they'd have investiture laws.)

Also, it just occurred to me that both my fix and this one lack inclusion of the Confederated church's bishoprics for investiture.

**Comment by Dryhad** [comment]
You're right, I meant to remove your event file but must have overlooked it while trying to figure out how Github works.
Confederated has been added in all the places where High Church and Strangite are, good catch.
Investiture laws are another matter. I _think_ it should be a simple fix but my attention is mostly on the EU4 converter at the moment so I don't have time to properly test it. I only did this much because I had already done most of it for my Canada submod. For now, at least, Ursulines can appoint their own Prioresses; I shall leave it to someone else to make it so doing so will anger the Abbess-General :)

**Pull request merged**
