### PR TITLE
Heresy for Sacred Heart

### PR DESCRIPTION
**Pull request by VoltSpark**
Not sure if this is usable, but I made a Virgin Mary cult as a heresy for Sacred Heart. Everything's been added except for a flag for the Religious Head.

The religious head has the same abilities as the President as the Quorum of the Twelve, and is always female except for the first one because I didn't want to break a history file.

Bishops are always women due to an on action event that fires whenever a bishop from the cult dies.

### CODE REVIEW

**Comment by romancapitalist** [comment]
Cool idea, but the localization files crash the program on launch, and even without them, all characters/provinces have "noreligion," and are thus unplayable. I'll try fiddling with 00_religion.txt to see if I can fix that, will report and test actual functionality if successful.

**Comment by romancapitalist** [comment]
Well, cleaning up the file some let Cetic at least show up; still unplayable. Argh, this file has more chaff than an prosperity gospel sermon.

**Comment by romancapitalist** [comment]
Okay, fixed the 00_religion issue; just paste a cleaned up code of the madre de dios section into the previous version of the file just after sagrado corazon but before the religion group ends. I used: 

[sagrado corazon]
madre_de_dios = {
graphical_culture = westerngfx
icon = 32
heresy_icon = 32
parent = sacred_heart
color = { 1 0.2 0.4 }
high_god_name =  GOD_THE_LORD GOD_THE_LORD GOD_THE_SUPREME GOD_THE_BLESSED_VIRGIN GOD_THE_MOTHER_OF_GOD GOD_OUR_LADY 
evil_god_names =  THE_DEVIL SATAN LUCIFER 
can_grant_divorce = yes
can_excommunicate = yes
can_grant_invasion_cb = yes
investiture = yes
can_call_crusade = no
priests_can_inherit = no
priests_can_marry = no
allow_rivermovement = yes
female_temple_holders = yes
feminist = yes
religious_clothing_head = 12
religious_clothing_priest = 1
crusade_name = CRUSADE
scripture_name = THE_BIBLE
priest_title = PADRE
intermarry = miclantec
intermarry = neomayan
intermarry = sol_invicta
intermarry = uahomche
has_coa_on_barony_only = yes
playable = yes
ai_peaceful = yes # Will make Hordes lose their super aggressiveness
hostile_within_group = yes
ai_convert_same_group = 1 # try to convert if ai_zeal is high
ai_convert_other_group = 2 # always try to convert
}
}
[pacific]

The padre (madre? fems show up as "baron") succession event works just fine, but it isn't triggering on previous holder's death. Not sure how to fix that, though. Localization's still throwing me for a loop, but seems to run stable so long as you leave the old files in place.

**Comment by VoltSpark** [comment]
That's interesting. Everything works fine on my machine. It probably has something to do with the fact that I copy-pasted the stuff from my machine into the text files on GitHub rather than re-uploading them. I'll move the Madre de Dios stuff into its own files on my system and upload them to see if that fixes the problem.

**Comment by thecookiemaker** [comment]
I compared this succession event to the several of the Ursuline Succession events. The Ursuline events have 

new_character = { ROOT = { any_demesne_title = { gain_title = PREVPREV } } }

whereas this one has 

new_character = { ROOT = { any_demesne_title = { grant_title_no_opinion = PREVPREV } } }

I am wondering if we need to use gain_title instead of grant_title_no_opinion

additionally the ursuline events have 

religion = ursuline
culture = quebecois

and this one has 

religion = ROOT
culture = ROOT

I don't know if this would have any effect as ROOT should pull the religion and culture from the person who died.

**Comment by thecookiemaker** [comment]
to fix the localisation you just need to add to am_flavor.csv

temple_baron_madre_de_dios;Padre;;;;;;;;;;;;;x
temple_baron_female_madre_de_dios;Madre;;;;;;;;;;;;;x

**Comment by romancapitalist** [comment]
I just discovered that your whole 00_on_action file is busted - I'm not getting events for pregnancy and birth, which led to an awkward discovery of a two-year-old son I didn't realize I had had.

I was referring to my problem with his localization crashing it on launch. Am I the only victim of that?

**Comment by VoltSpark** [comment]
Okay, I'm not sure what caused it, but looking at my commits to the branch, they're screwed up compared to my working local files. Currently in the process of isolating my changes where possible into their own files and uploading them properly rather than copy-pasting the changes into existing files.

Regarding the difference between my succession event for Madre de Dios bishoprics and the Ursuline succession events, again, my local files are working properly, so I'm assuming the way I submitted my changes screwed up all of the on_action events.

**Pull request closed without merging**
